"""empty message

Revision ID: e5b194c0b28b
Revises: d56e6a592965
Create Date: 2020-07-31 23:46:44.585110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b194c0b28b'
down_revision = 'd56e6a592965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
